FROM nvidia/cuda:9.0-cudnn7-runtime-ubuntu16.04

LABEL maintainer="Johannes Innerbichler <j.innerbichler@gmail.com>"

WORKDIR /

RUN pwd

ENV PYTHONIOENCODING UTF-8

# Pick up some TF dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        curl \
        libfreetype6-dev \
        libpng12-dev \
        libzmq3-dev \
        pkg-config \
        python3 \
        python3-numpy \
        python3-dev \
        python3-pip \
        python3-wheel \
        rsync \
        software-properties-common \
        unzip \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install and update pip tools
RUN pip3 install --upgrade pip
RUN pip3 install setuptools

# Install basic dependencies
RUN pip3 --no-cache-dir install \
        Pillow \
        h5py \
        ipykernel \
        jupyter \
        matplotlib \
        numpy \
        pandas \
        scipy \
        sklearn \
        && \
    python3 -m ipykernel.kernelspec

# Install TensorFlow GPU version.
RUN pip3 install tensorflow-gpu==1.6.0

# For CUDA profiling, TensorFlow requires CUPTI.
ENV LD_LIBRARY_PATH /usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH

# Install application dependencies
RUN pip3 --no-cache-dir install \
        spacy==2.0.9 \
        feedparser==5.2.1 \
        beautifulsoup4==4.6.0 \
        requests==2.18.4 \
        nltk==3.2.5 \
        html5lib==0.9999999 \
        h5py==2.7.1 \
        scipy==1.0.0 \
        tensorflow-gpu==1.6.0 \
        keras==2.1.5

RUN python3 -m spacy download en
RUN python3 -m spacy download de

EXPOSE 6006

COPY . .

ENTRYPOINT ["/usr/bin/python3", "char_rnn.py"]